:toc2:

= AgnosticV, vars for link:https://github.com/redhat-cop/agnosticd[AgnosticD]


This repo contains the variables needed for catalog items present in RHPDS and labs.opentlc.com.


== Goals

* Separate code and data
* Deploy the same way we develop, using a yaml file.
** Easy onboarding of lab and demo creators
* Contain catalog information (description, ...)
** Automatically generate catalog
* Lab creators and Administrator will easily contribute to agnosticV
* Easy maintenance (YAML files in a git repo)
* Introduce good processes for contributing
** Pull request
** Peer review
** Automatic tests
*** Syntax checking, Linters
*** Enforce policies (ex: "catalog item must have a description")
*** Detect non-documented variables
* Risk mitigation: no more manual operations on the deployment servers

== Structure

----
common.yaml

ACCOUNT/
    common.yaml

   CATALOGITEM1/
         common.yaml
         dev.yaml
         test.yaml
         prod.yaml


   CATALOGITEM2/
         common.yaml
         dev.yaml
         test.yaml
         prod.yaml
----

When deploying, you provide 3 things to the deployer (scripts or tower).

. _ACCOUNT_        (for example `gpte`, `openshift`, `sandboxes-gpte`, ...)
. _CATALOGITEM_    (for example `OCP_CLIENTVM`)
. _STAGE_          (`dev|test|prod`)


The variable of the yaml files are then merged in this order:

* `common.yaml`
* `ACCOUNT/common.yaml`
* `ACCOUNT/CATALOGITEM/common.yaml`
* `ACCOUNT/CATALOGITEM/STAGE*.yaml`   (_STAGE_ = `dev|test|prod`)

=== Merging strategy (not meta vars)

If a variable is defined in several YAML files, the definition in the last file has precedence over the others.

When a variable is present in more than one file:

* if it's a string, last definition will override previous
* if it's a list, last definition will override previous
* if it's a dictionary , all dictionaries will be *merged*

Regarding merging strategies for meta variables, see next section.

== Meta variables

Meta variables are just variables like any other, except they are not used for agnostic**d**. Instead they are useful to configure the way we want the deployment to happen, or anything that is done **before** or **outside** of agnostic**d**.

|=============================================
| Special variable | Purpose

| `agnosticv_meta`
| Dictionary containing variables used by the deployer scripts.

See implementation:  link:https://github.com/redhat-gpe/OPEN_Admin/blob/master/OPENTLC-Deployer/deploy_scripts/ALL_agnosticv.sh[`ALL_agnosticv.sh`] and link:https://github.com/redhat-gpe/OPEN_Admin/blob/master/OPENTLC-Deployer/OPEN-Deployer.agnosticv.sh[functions]

| `\\__meta__`
| Variables used by link:https://github.com/redhat-cop/babylon[Babylon]. See the dedicated section later in this Readme.
|=============================================

Variables in agnosticv are merged and then passed directly to `ansible-playbook` command.

If you want to change something happening *before* that, for example "specify what secrets to pass to agnosticd", you have to configure your catalog item (or account) using variables from the `agnosticv_meta` dictionary.

The following variables work with the BASH deployment scripts (Located in OPEN_Admin repository).

|=============================================
| Variable name | type | default | Purpose | Merging strategy

| `sandboxed`
| Boolean
| `false`
| Set to true to deploy in a sandbox (AWS only).
| Overwrite

| `virtualenv`
| String
| None
| When this variable is specified, the deployment script will activate the python virtualenv. Make sure the virtualenv exists on the admin host or create it first.

[underline]#For example#:

If you specify `virtualenv: openstack` and keep the default for `virtualenv_dir`, then the deployment script will perform: `source ${HOME}/virtualenvs/openstack/bin/activate` before running `ansible-playbook`.

| Overwrite

| `virtualenv_dir`
| String
| `~/virtualenvs`
| The directory where the virtualenvs are located
| Overwrite


| `nuke_sandbox`
| Boolean
| `true`
| Set to true to run link:https://github.com/rebuy-de/aws-nuke[aws-nuke] on the sandbox when the service retires (AWS only).

If set to `true`, the deletions of sandboxes are throttled to be gentle with AWS.

If set to `false`, the deletions of sandboxes can be run in parallel.
| Overwrite

| `params_to_variables`
| Dictionary
| see `link:common.yaml[]`
| This is the dictionary used to map ansible variables with BASH argument names passed by Cloudforms.  `<ansible-var>: <bash-arg>`
| Merge

| `secrets`
| List
| `[]`
| This list defines the secret files to load. `~/secrets/{{name}}.yml` in Admin host) or credentials (tower).
| Append

| `idle_after`
| Number
| `8`
| Number of hours after start/deploy to stop the environment.
| Overwrite

| `idle_after_deploy`
| Number
| `8`
| Number of hours after deploy to stop the environment.
| Overwrite

| `idle_after_start`
| Number
| `8`
| Number of hours after start to stop the environment.
| Overwrite

| `agnosticd_git_repo`
| String
| `'https://github.com/redhat-cop/agnosticd'`
| Repo URL for agnosticd
| Overwrite

| `agnosticd_git_tag_prefix`
| String
| `''`
| git tag prefix to check out. The tags are sorted using Version sort and the latest tag is picked.
| Overwrite

| `agnosticd_git_ref`
| String
| `development` if `stage=dev`
| git ref (branch, commit id, tag, ...) to checkout
| Overwrite

| `lifecycle_playbook`
| String
| `configs/{{ env_type }}/lifecycle.yml` if it exists, otherwise `lifecycle.yml`
| The playbook to use for start / stop / status actions. By default, the one in the config directory is used. If it doesn't exist, then the common link:https://github.com/redhat-cop/agnosticd/blob/development/ansible/lifecycle.yml[`lifecycle.yml`] is used, which just turns on/off the instances.
| Overwrite

| `deploy_with`
| String
| `local`
| The deployment suite to use. The default is `local`.

`local`: use the `ansible-playbook` command directly from the admin host

`babylon`: Use Babylon. You must set `agnosticv_meta.babylon` to configure it. You must also use the "babylon" virtualenv.
| Overwrite

| `babylon.kubeconfig`
| String
| None
| The kubeconfig file need to communicate with the Babylon OCP cluster. This file my exist locally on the admin host in `~/secrets/`
| Overwrite
|=============================================

.example
[source,yaml]
----
agnosticv_meta:
  secrets:
    - shush
    - dont_tell

  params_to_variables:
    user: student_name
----

=== Babylon backend

`agnosticv_meta` variables are not for babylon. But you can use them to tell the deployer script to use Babylon in the background.

The deployer script located on the admin hosts, `ALL_agnosticv.sh` has now the capability to deploy an environment using our link:https://github.com/redhat-cop/babylon[Babylon] clusters.
Instead of running the `ansible-playbook` locally on the admin host, the script will call Babylon components and let Babylon (down to Ansible Tower) handle the deployment.

In order to do that, there are a few things to add to your catalog item in agnosticv:

. In `agnosticv_meta`, set the following variables:
+
[source,yaml]
----
agnosticv_meta:
  # Instead of running ansible-playbook from the admin host,
  # tell ALL_agnosticv.sh to use babylon to deploy.
  deploy_with: babylon

  # Use a specific virtualenv that has all the k8s modules.
  # This is mandatory:
  virtualenv: babylon

  # Specify the kubeconfig to use to talk to the Babylon OCP cluster.
  # The kubeconfig file must exit in ~/secrets/ on the admin hosts.
  babylon:
    kubeconfig: babylon-prod.kubeconfig
----
+
|===========================
| kubeconfig | cluster

| `babydev.kubeconfig`
| link:https://github.com/redhat-gpe/babylon-private/tree/master/envs/babydev-ocp[babydev]
| `babytest.kubeconfig`
| link:https://github.com/redhat-gpe/babylon-private/tree/master/envs/babytest-ocp[babytest]
| `ocp-us-east-1.kubeconfig`
| link:https://github.com/redhat-gpe/babylon-private/tree/master/envs/ocp-us-east-1[ocp-us-east-1]
| `ocp-us-west-2.kubeconfig`
| link:https://github.com/redhat-gpe/babylon-private/tree/master/envs/ocp-us-east-1[ocp-us-west-2]
| `babylon-prod.kubeconfig`
| Link to current production cluster
|===========================

. Create `\\__meta__` dictionary containing the information needed by Babylon.
+
[source,yaml]
----
__meta__:
  catalog:
    namespace: gpte

    parameters:
      # Specify here all the variables passed by Cloudforms

  deployer:
    scm_ref: development
    scm_type: git
    scm_url: https://github.com/redhat-cop/agnosticd.git
    type: agnosticd

  # Here you must specify the secrets containing the variables used to deploy.
  secrets:
  - name: gpte
    namespace: gpte

  tower:
    organization: gpte
----

. Make sure you pass secrets. The current secrets living in `~/secrets` on the admin hosts were all imported as OpenShift secrets in the `gpte` namespace. So you can use the same name. For example:
+
[source,yaml]
----
agnosticv_meta:
  secrets:
    - gpte
    - ocp4_token
----
+
Becomes:
+
[source,yaml]
----
__meta__:
  secrets:
    - name: gpte
      namespace: gpte
    - name: ocp4_token
      namespace: gpte
----

==== Parameters passed from Cloudforms

Sometimes you want variables to be dynamic, and to come from a dialog in Cloudforms.

In order to pass variables from Cloudforms up to Babylon, you will need to pay attention to the following:

. Make sure the BASH parameter is translated to a variable by the `ALL_agnosticv.sh` script. This is defined by the `agnosticv_meta.params_to_variables` dictionary
+
[source,yaml]
----
agnosticv_meta:
  params_to_variables:
    appversion: ig_version
----
. Inform Babylon of all the variables you want to overwrite by using the `\\__meta__.catalog.parameters` list:
+
[souce,yaml]
----
__meta__:
  catalog:
    parameters:
    - name: cloud_tags
    - name: course_name
    - name: email
    - name: ipa_host_password
    - name: install_lets_encrypt_certificates
    - name: osrelease
    - name: platform
    - name: aws_region
    - name: student_name
    - name: ig_version
----
+
TIP: Remember to use link:https://github.com/redhat-cop/agnosticv/releases/[`agnosticv` CLI] to get all the variables for a catalog item. You can install it on your laptop. It's also installed on admin hosts (prod & dev).
+
[WARNING]
====
If the variable passed by Cloudforms is not in `\\__meta__.catalog.parameters`, in Babylon, the value for that variable will not be passed to Tower. It will fallback to the value defined in agnostic**v**.

Explanation: Everthing that is in `\\__meta__` is automatically parsed by the link:https://github.com/redhat-gpte-devopsautomation/agnosticv-operator[agnosticv-operator] to generate the AnarchyGovernors objects on the cluster. Those AnarchyGovernors contain the variables. If you want to allow those variables to be overwritten, you have to add them as parameters.
====


== Migrate a catalog item to agnosticv

== Checklist

. Ensure a jenkins pipeline is present for the catalog item
.. If not, ideally create the pipeline. See link:https://github.com/redhat-gpe/OPEN_Admin/blob/master/OPENTLC-Documentation/OPENTLC-Deployer_development_workflow/jenkins.adoc[jenkins.adoc] in OPEN_Admin.
. Run jenkins pipeline: should work.
. Translate variables present in the deployment script (`OPEN_Admin/OPEN-Deployer/deploy_scripts/`) into YAML link:https://github.com/redhat-gpe/agnosticv[`agnosticv`]
. Go into CloudForms and change the remote script
.. automation / automate / explorer / OPEN-Ansible-Deployer / State Machines / ... / remoteScript
+
----
/home/opentlc-mgr/OPEN_Admin/OPENTLC-Deployer/deploy_scripts/${#className}.sh
to
/home/opentlc-mgr/OPEN_Admin/OPENTLC-Deployer/deploy_scripts/ALL_agnosticv.sh
----
. Order service
.. test stop action from Clouforms
.. test start action from Clouforms
.. test status action from Clouforms
. Run jenkins pipeline: should work.
. Add comment in the old script to point to the new script and to agnosticv definition files.
+
.Warning example
----
########################################################################
#
#
#           /!\ THIS FILE IS NOT USED ANYMORE /!\
#
#
#   The DEV CLIENT VM catalog item vars are now defined here:
# https://github.com/redhat-gpe/agnosticv/blob/master/common.yaml
# https://github.com/redhat-gpe/agnosticv/blob/master/gpte/common.yaml
# https://github.com/redhat-gpe/agnosticv/blob/master/gpte/OCP_CLIENTVM/dev.yaml
#
#
#   The deployment script used now is ALL_agnosticv.sh
#
#
########################################################################
----

. After a month, grep the logs to ensure the old script was not called.
** If it was, it means there is another catalog item that is using the script. Investigate.
** If not, delete the old script.

----
########################################################################
# RHTE: for shared clusters, use account: RHTE
# RHTE: for cluster per studnet, use sandboxes-GPTE *Does not work via CLI*
# RHTE: Secrets: ssh to bastion to find rhte-ocp4
########################################################################
----

==  Running AgnosticD and AgnosticV via CLI

* First, use link:https://github.com/redhat-cop/agnosticv/releases/[`agnosticv` CLI] to get a YAML file of your config.  Indicate the catalog item path to merge the variables.
+
.Example
----
cd agnosticv
agnosticv --merge sandboxes-gpte/RHTE_A0007/dev.yml > $HOME/config.yaml
----
** For more information about the agnosticv CLI, see agnosticv link:https://github.com/redhat-cop/agnosticv[Readme]

* Then run your agnosticD deployer
+
.Example `ansible-playbook` agnosticD
----
#!/bin/bash
ansible-playbook ./ansible/main.yml -e @./config.yaml -e @./secret.yaml -e guid=<a GUID>
----
